[package]
name = "bangs"
version = "0.1.0"
authors = ["Smitty <me@smitop.com>"]
edition = "2018"

[dependencies]
regex = { version = "1.4.2", default-features = false, features = ["perf", "std"] } # don't use unicode
lazy_static = "1.4.0"
urlencoding = "1.1.1"

[[bin]]
name = "cmd"
